platform :ios do
  lane :debug do
    sh("cd .. && react-native run-ios")
    sh("cd .. && node node_modules/.bin/haul --config ./config/dev.haul.js --platform ios")
  end

  lane :release do
    ENV["BUNDLE_CONFIG"] = "config/prod.haul.js"
    ENV["OUT_PATH"] = "./ios/Example/main.jsbundle"
    ENV["ASS_PATH"] = "./ios/Example/assets"
    gym(
      project: "ios/Example.xcodeproj",
      configuration: "Release",
      scheme: "Example",
      silent: true,
      clean: true,
      sdk: "iphoneos11.2",
    )
  end

  lane :test_unit do
    sh("cd .. && node node_modules/.bin/jest")
  end

  lane :test_e2e do
    ENV["BUNDLE_CONFIG"] = "config/prod.haul.js"
    xcodebuild(
      project: "ios/Example.xcodeproj",
      scheme: "Example",
      configuration: "Release",
      sdk: "iphonesimulator",
      derivedDataPath: "ios/build",
    )
    sh("cd .. && node node_modules/.bin/detox test -c ios.sim.release")
  end
  
  #TODO: add test_e2e_debug runner
end

platform :android do
  lane :debug do
    sh("cd .. && react-native run-android")
    sh("cd .. && node node_modules/.bin/haul --config ./config/dev.haul.js --platform android")
  end
  
  lane :release do
    gradle(
      project_dir: "android",
      task: "assembleRelease",
      properties: {
        "bundleInDebug" => false,
        "bundleInRelease" => true,
        "configPath" => "prod.haul"
      }
    )
  end

  lane :test_unit do
    sh("cd .. && node node_modules/.bin/jest")
  end

  lane :test_e2e do
    gradle(
      project_dir: "android",
      task: "assembleRelease",
      properties: {
        "bundleInDebug" => false,
        "bundleInRelease" => true,
        "configPath" => "prod.haul"
      },
      system_properties: {
        "testBuildType" => "release"
      }
    )
    gradle(
      project_dir: "android",
      task: "assembleAndroidTest",
      properties: {
        "bundleInDebug" => false,
        "bundleInRelease" => true,
        "configPath" => "prod.haul"
      },
      system_properties: {
        "testBuildType" => "release"
      }
    )
    sh("cd .. && node node_modules/.bin/detox test -c android.emu.release")
  end

  #TODO: add test_e2e_debug runner
end
